#!/bin/sh

for i in $*
do
    git log --pretty=format:"%x09%ad%x09%s" --date=short | grep "\PROJECT_NAME-$i \[" | awk '!x[$1$3]++' | cut -d']' -f1 | sed 's/$/]/' | awk '{ gsub(/NAME_REGEX_1/, "ROLE1"); print }' | awk '{ gsub(/NAME_REGEX_2/, "ROLE2"); print }'| sed 's/[,|&]*//g' | sed 's/[ ]*//g' | sed -e ': a' -e 's/\(\[[^][]*\)\([A-Z][A-Z][A-Z]\)\([^][]*\)\2/\1\2\3/' -e 't a' | perl -ne '$H{$_}++ or print' |awk '{gsub(/ROLE1/, "\033[32mROLE1\033[0m"); print}'| awk '{ gsub(/ROLE2/, "\033[34mROLE2\033[0m"); print }' | tee /dev/tty |rev|uniq -f1 | rev |wc -l | sed 's/$/ days total/'|  sed G
done

